package com.commandlinegirl.algorithms.leetcode;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * https://leetcode.com/problems/find-the-difference/
 */
public class FindTheDifference {

    /**
     * Time complexity: O(|s| + |t|)
     * Memory complexity: O(1)
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
        int xor = 0;
        for (char c : s.toCharArray())
            xor ^= c;
        for (char c : t.toCharArray())
            xor ^= c;
        return (char) xor;
    }
}
